In [1]:
import numpy
numpy._version_


AttributeError: module 'numpy' has no attribute '_version_'

In [2]:
clear


In [3]:
import numpy
numpy.__version__

'1.21.2'

In [4]:
import numpy as np
np.<TAB>

SyntaxError: invalid syntax (<ipython-input-4-2ffaa2f279db>, line 2)

In [5]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [6]:
x1


array([5, 0, 3, 3, 7, 9])

In [7]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [8]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [9]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [10]:
print("dtype:", x3.dtype)

dtype: int64


In [11]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x[:5]


array([0, 1, 2, 3, 4])

In [19]:
x[5:]
x[4:7]

array([4, 5, 6])

In [23]:
x[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])